version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challenge_magazord_app
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: challenge_magazord_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magazord
      MYSQL_USER: magazord
      MYSQL_PASSWORD: magazord
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
